name: noti_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  go_router: ^15.1.2
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  animate_do: ^4.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.6
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/no-image.jpg
    - assets/loaders/bottle-loader.gif
